[package]
name = "slurm-monitor-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.7", features = ["derive", "wrap_help", "unicode"] }
itertools = "0.13.0"
signal-hook = "0.3.17"
